### ISSUE TITLE
Braking force technology conflicts

### ISSUE THREAD

**Issue by 1avek1** [LuziferSenpai/Battle-Locomotives#2]
Unconditionally adding braking force research when another mod making it infinite breaks the game, so it won't start at all.

It can now be seen under Factorio 0.17.79 with the  [Stupidly Awesome Fuel](https://mods.factorio.com/mod/stupidly-awesome-fuel) mod. May potentially happen with other mods.

Can a setting be added to disable these techs?

**Comment by LuziferSenpai** [comment]
No, sry. I will not change something there. The other Dev should check of something is getting changed.
